apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`uptime.local.gemms.network`)
      kind: Rule
      services:
        - name: uptime-kuma
          port: 3001
  tls:
    secretName: local-gemms-network-tls
